typography_spectrum: 0.1408090372569859
color:
  brandStrength: 0.8784890347160399
  lightness: 0.01517767715267837
  saturation: 0.7069611290935427
  rhythmicContrast: 0.402029829332605
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
layout_spectrum: 0.3937868282664567
name: Mobilis Pro
title: We Create The Future
description: To live in
